trigger: none
pool: 
  name: LinuxPool

stages:
  - stage: Build
    displayName: "Build Java Application"
    jobs:
      - job: buildJob
        steps:
          - checkout: self
          - task: Maven@4
            inputs:
              azureSubscription: 'DjAzureSPNConnection'
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Docker
    displayName: "Build & Push Docker Image"
    dependsOn: Build
    jobs:
      - job: DockerBuild
        steps:
          - download: current
            artifact: drop
          - task: Docker@2
            inputs:
              containerRegistry: 'docker0395'
              repository: 'dhanu0395/myweb-app'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: '$(Pipeline.Workspace)/drop'
              tags: |
                latest

  - stage: Deploy
    displayName: "Deploy Container"
    dependsOn: Docker
    jobs:
    - job: RunContainer
      steps:
        - script: |
            echo "Pulling latest image..."
            docker pull dhanu0395/myweb-app:latest
            echo "Running container..."
            docker run -d -p 6070:8080 dhanu0395/myweb-app:latest
          displayName: "Deploy Container"

          #           docker-compose -p 6070:8080 -f docker-compose.yml up -d
