trigger: none
pool: 
  name: LinuxPool

stages:
  - stage: buildStage
    displayName: "Build Java Application"
    jobs:
      - job: buildJob
        steps:
          - checkout: self
          - task: Maven@4
            inputs:
              azureSubscription: 'DjAzureSPNConnection'
              mavenPomFile: 'pom.xml'
              goals: 'package'
              publishJUnitResults: true
              testResultsFiles: '**/surefire-reports/TEST-*.xml'
              javaHomeOption: 'JDKVersion'
              mavenVersionOption: 'Default'
              mavenAuthenticateFeed: false
              effectivePomSkip: false
              sonarQubeRunAnalysis: false
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/target'
              ArtifactName: 'drop'
              publishLocation: 'Container'

  - stage: Docker
    displayName: "Build & Push Docker Image"
    dependsOn: Build
    jobs:
      - job: DockerBuild
        steps:
          - task: DockerCompose@1
            inputs:
              containerregistrytype: 'Container Registry'
              dockerRegistryEndpoint: 'docker0395'
              dockerComposeFile: '**/docker-compose.yml'
              action: 'Build services'
    



